language: julia

os: linux

julia: 1.2

addons:
    apt:
        packages:
            - python3
            - python3-setuptools
            - python3-pip

env:
    global:
        - PYTHON=$(which python3)
        - GEM_HOME=$HOME/.gems
        - PATH="$GEM_HOME/bin:$HOME/.local/bin:$PATH"

install:
    - sudo python3 -m pip install --upgrade pip
    - python3 -m pip install --user nbconvert
    - gem install bundler jekyll
    - bundle install

jobs:
    include:
        - state: "Website"
          julia: 1.2
          os: linux
          script:
              - julia --project=. -e 'using Pkg; Pkg.instantiate()'
              - julia --project=. make.jl
          after_success: skip
