name: Build and Deploy
on:
  push:
    branches:
      staging
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.5'

      - name: Cache Hugo
        id: cache-go
        uses: actions/cache@v2
        with:
          path: /home/runner/go
          key: ${{ runner.os }}-go
          restore-keys: ${{ runner.os }}-go

      - name: Install Hugo
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          mkdir -p $GOPATH/src/github.com/gohugoio
          pushd $GOPATH/src/github.com/gohugoio
          git clone https://github.com/gohugoio/hugo
          cd hugo
          go install --tags extended
          popd
          hugo version
        env:
          GOPATH: /home/runner/go

      - name: Install Jupyter
        run: |
            pip3 install -U pip setuptools pygments
            pip3 install jupyter

      - name: Build Site
        run: make
        env:
          GOPATH: /home/runner/go

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
          CLEAN: true
